weights_save_path: ../model/ntu_rgb+d/Model2_xview.pt
weights_path: ../model/ntu_rgb+d/Model_xview.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/eval_data.npy
  label_path: ../data/NTU-RGB-D/xview/eval_label.pkl

# model
model: net.svit.Model
model_args:
  temporal_size: 300
  temporal_stride: 2
  num_joint: 25
  num_classes: 60
  dim: 512
  depth: 6
  heads: 8
  mlp_dim: 512


# optim
optimizer: Adam
base_lr: 0.0012
weight_decay: 0.0001

# lr_scheduler
step_size: 50
scheduler_gamma: 0.1

# test
phase: eval
device: [0,1,2,3]
test_batchsize: 128