
weights_path: ../model/ntu_rgb+d/Multi_scale_model_xview.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/eval_data.npy
  label_path: ../data/NTU-RGB-D/xview/eval_label.pkl

# model
model: net.svit.Multi_scale_model
model_args:
  temporal_size: 300
  temporal_stride_1: 2
  temporal_stride_2: 10
  num_joint: 25
  num_classes: 60
  dim: 512
  depth: 6
  heads: 8
  dim_head: 64
  mlp_dim: 512
  dropout: 0.
  emb_dropout: 0.


# optim
optimizer: Adam
base_lr: 0.0012
weight_decay: 0.0001

# lr_scheduler
step_size: 50
scheduler_gamma: 0.1

# test
phase: eval
device: [0,1,2,3]
test_batchsize: 128