# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/train_data.npy
  label_path: ../data/NTU-RGB-D/xview/train_label.pkl
test_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/eval_data.npy
  label_path: ../data/NTU-RGB-D/xview/eval_label.pkl


# model
weights_save_path: ../model/ntu_rgb+d/Model3_xview.pt
weights_path: ../model/ntu_rgb+d/Model3_xview.pt
model: net.svit.Model3
model_args:
  temporal_size: 300
  temporal_stride: 20
  num_joint: 25
  num_classes: 60
  dim: 128
  depth: 6
  dim_head: 64
  heads: 8
  mlp_dim: 256
  dropout: 0.5

# optim
optimizer: Adam
base_lr: 0.0012
weight_decay: 0.0000

# lr_scheduler
lr_scheduler: Cos
T_max : 50

# training
device: [0,1,2,3]
train_batchsize: 64
test_batchsize: 64
num_epoch: 150
test_interval: 5