

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/train_data.npy
  label_path: ../data/NTU-RGB-D/xview/train_label.pkl
test_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/eval_data.npy
  label_path: ../data/NTU-RGB-D/xview/eval_label.pkl

# model
weights_save_path: ../model/ntu_rgb+d/Multi_scale_model_xview.pt
weights_path: ../model/ntu_rgb+d/Multi_scale_model_xview.pt
model: net.svit.Multi_scale_model
model_args:
  temporal_size: 300
  temporal_stride_1: 2
  temporal_stride_2: 10
  num_joint: 25
  num_classes: 60
  dim: 512
  depth: 6
  heads: 8
  dim_head: 64
  mlp_dim: 512
  dropout: 0.
  emb_dropout: 0.


# optim
optimizer: Adam
base_lr: 0.0015
weight_decay: 0.0001

# lr_scheduler
lr_scheduler: Cos
T_max : 50

# training
device: [0]
train_batchsize: 128
test_batchsize: 128
num_epoch: 150
test_interval: 5
