

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/train_data.npy
  label_path: ../data/NTU-RGB-D/xview/train_label.pkl
test_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/eval_data.npy
  label_path: ../data/NTU-RGB-D/xview/eval_label.pkl

# model
model: net.svit.Model
model_args:
  temporal_size: 300
  temporal_stride: 4
  num_joint: 25
  num_classes: 60
  dim: 512
  depth: 4
  heads: 8
  mlp_dim: 512


# optim
optimizer: Adam
base_lr: 0.0012
weight_decay: 0.0001

# lr_scheduler
step_size: 50
scheduler_gamma: 0.1

# training
device: [0,1,2,3]
train_batchsize: 32
test_batchsize: 32
num_epoch: 80
test_interval: 5



