
# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/train_data.npy
  label_path: ../data/NTU-RGB-D/xview/train_label.pkl
test_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/eval_data.npy
  label_path: ../data/NTU-RGB-D/xview/eval_label.pkl

# model
weights_save_path: ../model/ntu_rgb+d/Model2_xview.pt
#weights_path: ../model/ntu_rgb+d/Model2_xview.pt
model: net.svit.Model2
model_args:
  temporal_size: 300
  temporal_stride: 2
  num_joint: 25
  num_classes: 60
  s_dim: 32
  depth: 3
  heads: 8
  s_dim_head: 4
  s_mlp_dim: 32


# optim
optimizer: Adam
base_lr: 0.0007
weight_decay: 0.01
#momentum: 0.9

# lr_scheduler
step_size: 100
scheduler_gamma: 0.1

# training
device: [0,1,2,3]
train_batchsize: 64
test_batchsize: 64
num_epoch: 80
test_interval: 5
