

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/train_data.npy
  label_path: ../data/NTU-RGB-D/xview/train_label.pkl
test_feeder_args:
  data_path: ../data/NTU-RGB-D/xview/eval_data.npy
  label_path: ../data/NTU-RGB-D/xview/eval_label.pkl

# model
weights_save_path: ../model/ntu_rgb+d/Model_xsub.pt
weights_path: ../model/ntu_rgb+d/Model_xsub.pt
model: net.svit.Model
model_args:
  temporal_size: 300
  temporal_stride: 2
  num_joint: 25
  num_classes: 60
  dim: 512
  depth: 6
  heads: 8
  mlp_dim: 512
  dropout: 0.4
  emb_dropout: 0.4

# optim
optimizer: Adam
base_lr: 0.0012
weight_decay: 0.0001

# lr_scheduler
lr_scheduler: Cos         # must be Step or Cos
T_max: 50


# training
device: [0,1,2,3]
train_batchsize: 128
test_batchsize: 128
num_epoch: 150
test_interval: 5
